name: Update folder READMEs

on:
  push:
    branches: [ main, master ]
    paths:
      - "**/*.md"
      - "scripts/gen_readmes.py"
  workflow_dispatch:

permissions:
  contents: write  # allow the workflow to commit changes

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate folder READMEs
        run: |
          python scripts/gen_readmes.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update folder READMEs"
          branch: ${{ github.ref_name }}
